id: P000401
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:38:01.956732
source_metadata:
  id: bdr:W1KG4522
  title: ཚད་མའི་རིགས་ལམ་
  author: ''
  volumes:
    63cc836c7fc742e2b451ecd37736e7b8:
      image_group_id: I1KG4541
      title: Volume 1 of tshad ma'i rigs lam
      volume_number: 1
      total_pages: 162
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
